// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
// 	protoc        v6.32.1
// source: auth.proto
========
// 	protoc        v6.33.0
// source: auth_service/auth.proto
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go

package auth_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Register user
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	SecondName    string                 `protobuf:"bytes,5,opt,name=second_name,json=secondName,proto3" json:"second_name,omitempty"`
	ThirdName     string                 `protobuf:"bytes,6,opt,name=third_name,json=thirdName,proto3" json:"third_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

<<<<<<<< HEAD:v1/auth/api/auth.pb.go
func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_auth_proto_msgTypes[0]
========
func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_auth_service_auth_proto_msgTypes[0]
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

<<<<<<<< HEAD:v1/auth/api/auth.pb.go
func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
========
func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_auth_proto_msgTypes[0]
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

<<<<<<<< HEAD:v1/auth/api/auth.pb.go
// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
========
// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_auth_proto_rawDescGZIP(), []int{0}
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
}

func (x *RegisterRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterRequest) GetSecondName() string {
	if x != nil {
		return x.SecondName
	}
	return ""
}

func (x *RegisterRequest) GetThirdName() string {
	if x != nil {
		return x.ThirdName
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

<<<<<<<< HEAD:v1/auth/api/auth.pb.go
func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_auth_proto_msgTypes[1]
========
func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_auth_service_auth_proto_msgTypes[1]
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

<<<<<<<< HEAD:v1/auth/api/auth.pb.go
func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
========
func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_auth_proto_msgTypes[1]
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

<<<<<<<< HEAD:v1/auth/api/auth.pb.go
// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
========
// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_auth_proto_rawDescGZIP(), []int{1}
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
}

func (x *RegisterResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RegisterResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RegisterResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// Login user
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_service_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_auth_service_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// Get user
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	mi := &file_auth_proto_msgTypes[2]
========
	mi := &file_auth_service_auth_proto_msgTypes[4]
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	mi := &file_auth_proto_msgTypes[2]
========
	mi := &file_auth_service_auth_proto_msgTypes[4]
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	return file_auth_proto_rawDescGZIP(), []int{2}
========
	return file_auth_service_auth_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
}

func (x *GetUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	SecondName    string                 `protobuf:"bytes,4,opt,name=second_name,json=secondName,proto3" json:"second_name,omitempty"`
	ThirdName     string                 `protobuf:"bytes,5,opt,name=third_name,json=thirdName,proto3" json:"third_name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	mi := &file_auth_proto_msgTypes[3]
========
	mi := &file_auth_service_auth_proto_msgTypes[5]
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	mi := &file_auth_proto_msgTypes[3]
========
	mi := &file_auth_service_auth_proto_msgTypes[5]
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	return file_auth_proto_rawDescGZIP(), []int{3}
========
	return file_auth_service_auth_proto_rawDescGZIP(), []int{5}
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
}

func (x *GetUserResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetUserResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetUserResponse) GetSecondName() string {
	if x != nil {
		return x.SecondName
	}
	return ""
}

func (x *GetUserResponse) GetThirdName() string {
	if x != nil {
		return x.ThirdName
	}
	return ""
}

func (x *GetUserResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Refresh token
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	mi := &file_auth_proto_msgTypes[4]
========
	mi := &file_auth_service_auth_proto_msgTypes[6]
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	mi := &file_auth_proto_msgTypes[4]
========
	mi := &file_auth_service_auth_proto_msgTypes[6]
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	return file_auth_proto_rawDescGZIP(), []int{4}
========
	return file_auth_service_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshTokenRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	mi := &file_auth_proto_msgTypes[5]
========
	mi := &file_auth_service_auth_proto_msgTypes[7]
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	mi := &file_auth_proto_msgTypes[5]
========
	mi := &file_auth_service_auth_proto_msgTypes[7]
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	return file_auth_proto_rawDescGZIP(), []int{5}
========
	return file_auth_service_auth_proto_rawDescGZIP(), []int{7}
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// Update user
type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	SecondName    string                 `protobuf:"bytes,4,opt,name=second_name,json=secondName,proto3" json:"second_name,omitempty"`
	ThirdName     string                 `protobuf:"bytes,5,opt,name=third_name,json=thirdName,proto3" json:"third_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	mi := &file_auth_proto_msgTypes[6]
========
	mi := &file_auth_service_auth_proto_msgTypes[8]
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	mi := &file_auth_proto_msgTypes[6]
========
	mi := &file_auth_service_auth_proto_msgTypes[8]
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	return file_auth_proto_rawDescGZIP(), []int{6}
========
	return file_auth_service_auth_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateUserRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
}

func (x *UpdateUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUserRequest) GetSecondName() string {
	if x != nil {
		return x.SecondName
	}
	return ""
}

func (x *UpdateUserRequest) GetThirdName() string {
	if x != nil {
		return x.ThirdName
	}
	return ""
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	SecondName    string                 `protobuf:"bytes,3,opt,name=second_name,json=secondName,proto3" json:"second_name,omitempty"`
	ThirdName     string                 `protobuf:"bytes,4,opt,name=third_name,json=thirdName,proto3" json:"third_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	mi := &file_auth_proto_msgTypes[7]
========
	mi := &file_auth_service_auth_proto_msgTypes[9]
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	mi := &file_auth_proto_msgTypes[7]
========
	mi := &file_auth_service_auth_proto_msgTypes[9]
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	return file_auth_proto_rawDescGZIP(), []int{7}
========
	return file_auth_service_auth_proto_rawDescGZIP(), []int{9}
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
}

func (x *UpdateUserResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUserResponse) GetSecondName() string {
	if x != nil {
		return x.SecondName
	}
	return ""
}

func (x *UpdateUserResponse) GetThirdName() string {
	if x != nil {
		return x.ThirdName
	}
	return ""
}

// Revoke token
type RevokeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	mi := &file_auth_proto_msgTypes[8]
========
	mi := &file_auth_service_auth_proto_msgTypes[10]
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	mi := &file_auth_proto_msgTypes[8]
========
	mi := &file_auth_service_auth_proto_msgTypes[10]
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	return file_auth_proto_rawDescGZIP(), []int{8}
========
	return file_auth_service_auth_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeTokenRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
}

func (x *RevokeTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// Delete user
type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	mi := &file_auth_proto_msgTypes[9]
========
	mi := &file_auth_service_auth_proto_msgTypes[11]
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	mi := &file_auth_proto_msgTypes[9]
========
	mi := &file_auth_service_auth_proto_msgTypes[11]
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	return file_auth_proto_rawDescGZIP(), []int{9}
========
	return file_auth_service_auth_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteUserRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

<<<<<<<< HEAD:v1/auth/api/auth.pb.go
var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x04auth\x1a\x1bgoogle/protobuf/empty.proto\"\xa4\x01\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
========
var File_auth_service_auth_proto protoreflect.FileDescriptor

const file_auth_service_auth_proto_rawDesc = "" +
	"\n" +
	"\x17auth_service/auth.proto\x12\x04auth\x1a\x1bgoogle/protobuf/empty.proto\"\xc5\x01\n" +
	"\x0fRegisterRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1d\n" +
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1f\n" +
	"\vsecond_name\x18\x05 \x01(\tR\n" +
	"secondName\x12\x1d\n" +
	"\n" +
	"third_name\x18\x06 \x01(\tR\tthirdName\"s\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\"c\n" +
	"\fLoginRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"p\n" +
	"\rLoginResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\"L\n" +
	"\x0eGetUserRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\xbe\x01\n" +
	"\x0fGetUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1f\n" +
	"\vsecond_name\x18\x04 \x01(\tR\n" +
	"secondName\x12\x1d\n" +
	"\n" +
	"third_name\x18\x05 \x01(\tR\tthirdName\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"]\n" +
	"\x13RefreshTokenRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"^\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"\xae\x01\n" +
	"\x11UpdateUserRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1f\n" +
	"\vsecond_name\x18\x04 \x01(\tR\n" +
	"secondName\x12\x1d\n" +
	"\n" +
	"third_name\x18\x05 \x01(\tR\tthirdName\"\x8c\x01\n" +
	"\x12UpdateUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1f\n" +
	"\vsecond_name\x18\x03 \x01(\tR\n" +
	"secondName\x12\x1d\n" +
	"\n" +
	"third_name\x18\x04 \x01(\tR\tthirdName\"\\\n" +
	"\x12RevokeTokenRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"O\n" +
	"\x11DeleteUserRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId2\xba\x03\n" +
	"\vAuthService\x129\n" +
	"\bRegister\x12\x15.auth.RegisterRequest\x1a\x16.auth.RegisterResponse\x120\n" +
	"\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x126\n" +
	"\aGetUser\x12\x14.auth.GetUserRequest\x1a\x15.auth.GetUserResponse\x12E\n" +
	"\fRefreshToken\x12\x19.auth.RefreshTokenRequest\x1a\x1a.auth.RefreshTokenResponse\x12?\n" +
	"\n" +
	"UpdateUser\x12\x17.auth.UpdateUserRequest\x1a\x18.auth.UpdateUserResponse\x12?\n" +
	"\vRevokeToken\x12\x18.auth.RevokeTokenRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\n" +
	"DeleteUser\x12\x17.auth.DeleteUserRequest\x1a\x16.google.protobuf.EmptyB\x12Z\x10proto/auth_protob\x06proto3"

var (
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_auth_proto_goTypes = []any{
	(*CreateUserRequest)(nil),    // 0: auth.CreateUserRequest
	(*CreateUserResponse)(nil),   // 1: auth.CreateUserResponse
	(*GetUserRequest)(nil),       // 2: auth.GetUserRequest
	(*GetUserResponse)(nil),      // 3: auth.GetUserResponse
	(*RefreshTokenRequest)(nil),  // 4: auth.RefreshTokenRequest
	(*RefreshTokenResponse)(nil), // 5: auth.RefreshTokenResponse
	(*UpdateUserRequest)(nil),    // 6: auth.UpdateUserRequest
	(*UpdateUserResponse)(nil),   // 7: auth.UpdateUserResponse
	(*RevokeTokenRequest)(nil),   // 8: auth.RevokeTokenRequest
	(*DeleteUserRequest)(nil),    // 9: auth.DeleteUserRequest
	(*emptypb.Empty)(nil),        // 10: google.protobuf.Empty
}
var file_auth_proto_depIdxs = []int32{
	0,  // 0: auth.AuthService.CreateUser:input_type -> auth.CreateUserRequest
	2,  // 1: auth.AuthService.GetUser:input_type -> auth.GetUserRequest
	4,  // 2: auth.AuthService.RefreshToken:input_type -> auth.RefreshTokenRequest
	6,  // 3: auth.AuthService.UpdateUser:input_type -> auth.UpdateUserRequest
	8,  // 4: auth.AuthService.RevokeToken:input_type -> auth.RevokeTokenRequest
	9,  // 5: auth.AuthService.DeleteUser:input_type -> auth.DeleteUserRequest
	1,  // 6: auth.AuthService.CreateUser:output_type -> auth.CreateUserResponse
	3,  // 7: auth.AuthService.GetUser:output_type -> auth.GetUserResponse
	5,  // 8: auth.AuthService.RefreshToken:output_type -> auth.RefreshTokenResponse
	7,  // 9: auth.AuthService.UpdateUser:output_type -> auth.UpdateUserResponse
	10, // 10: auth.AuthService.RevokeToken:output_type -> google.protobuf.Empty
	10, // 11: auth.AuthService.DeleteUser:output_type -> google.protobuf.Empty
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
========
	file_auth_service_auth_proto_rawDescOnce sync.Once
	file_auth_service_auth_proto_rawDescData []byte
)

func file_auth_service_auth_proto_rawDescGZIP() []byte {
	file_auth_service_auth_proto_rawDescOnce.Do(func() {
		file_auth_service_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_service_auth_proto_rawDesc), len(file_auth_service_auth_proto_rawDesc)))
	})
	return file_auth_service_auth_proto_rawDescData
}

var file_auth_service_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_auth_service_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),      // 0: auth.RegisterRequest
	(*RegisterResponse)(nil),     // 1: auth.RegisterResponse
	(*LoginRequest)(nil),         // 2: auth.LoginRequest
	(*LoginResponse)(nil),        // 3: auth.LoginResponse
	(*GetUserRequest)(nil),       // 4: auth.GetUserRequest
	(*GetUserResponse)(nil),      // 5: auth.GetUserResponse
	(*RefreshTokenRequest)(nil),  // 6: auth.RefreshTokenRequest
	(*RefreshTokenResponse)(nil), // 7: auth.RefreshTokenResponse
	(*UpdateUserRequest)(nil),    // 8: auth.UpdateUserRequest
	(*UpdateUserResponse)(nil),   // 9: auth.UpdateUserResponse
	(*RevokeTokenRequest)(nil),   // 10: auth.RevokeTokenRequest
	(*DeleteUserRequest)(nil),    // 11: auth.DeleteUserRequest
	(*emptypb.Empty)(nil),        // 12: google.protobuf.Empty
}
var file_auth_service_auth_proto_depIdxs = []int32{
	0,  // 0: auth.AuthService.Register:input_type -> auth.RegisterRequest
	2,  // 1: auth.AuthService.Login:input_type -> auth.LoginRequest
	4,  // 2: auth.AuthService.GetUser:input_type -> auth.GetUserRequest
	6,  // 3: auth.AuthService.RefreshToken:input_type -> auth.RefreshTokenRequest
	8,  // 4: auth.AuthService.UpdateUser:input_type -> auth.UpdateUserRequest
	10, // 5: auth.AuthService.RevokeToken:input_type -> auth.RevokeTokenRequest
	11, // 6: auth.AuthService.DeleteUser:input_type -> auth.DeleteUserRequest
	1,  // 7: auth.AuthService.Register:output_type -> auth.RegisterResponse
	3,  // 8: auth.AuthService.Login:output_type -> auth.LoginResponse
	5,  // 9: auth.AuthService.GetUser:output_type -> auth.GetUserResponse
	7,  // 10: auth.AuthService.RefreshToken:output_type -> auth.RefreshTokenResponse
	9,  // 11: auth.AuthService.UpdateUser:output_type -> auth.UpdateUserResponse
	12, // 12: auth.AuthService.RevokeToken:output_type -> google.protobuf.Empty
	12, // 13: auth.AuthService.DeleteUser:output_type -> google.protobuf.Empty
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

<<<<<<<< HEAD:v1/auth/api/auth.pb.go
func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
========
func init() { file_auth_service_auth_proto_init() }
func file_auth_service_auth_proto_init() {
	if File_auth_service_auth_proto != nil {
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
========
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_service_auth_proto_rawDesc), len(file_auth_service_auth_proto_rawDesc)),
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
<<<<<<<< HEAD:v1/auth/api/auth.pb.go
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
========
		GoTypes:           file_auth_service_auth_proto_goTypes,
		DependencyIndexes: file_auth_service_auth_proto_depIdxs,
		MessageInfos:      file_auth_service_auth_proto_msgTypes,
	}.Build()
	File_auth_service_auth_proto = out.File
	file_auth_service_auth_proto_goTypes = nil
	file_auth_service_auth_proto_depIdxs = nil
>>>>>>>> d1c380f0453de486a3eff6d29a958ef43a5aab04:app/protos/auth_service/auth.pb.go
}
