// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: company.proto

package company_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Health
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_company_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{0}
}

func (x *HealthRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        string                 `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_company_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

// CreateCompany
type CreateCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompanyRequest) Reset() {
	*x = CreateCompanyRequest{}
	mi := &file_company_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompanyRequest) ProtoMessage() {}

func (x *CreateCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompanyRequest.ProtoReflect.Descriptor instead.
func (*CreateCompanyRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCompanyRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *CreateCompanyRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *CreateCompanyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateCompanyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyUuid   string                 `protobuf:"bytes,1,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompanyResponse) Reset() {
	*x = CreateCompanyResponse{}
	mi := &file_company_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompanyResponse) ProtoMessage() {}

func (x *CreateCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompanyResponse.ProtoReflect.Descriptor instead.
func (*CreateCompanyResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCompanyResponse) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

// GetCompany
type GetCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CompanyUuid   string                 `protobuf:"bytes,3,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyRequest) Reset() {
	*x = GetCompanyRequest{}
	mi := &file_company_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyRequest) ProtoMessage() {}

func (x *GetCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{4}
}

func (x *GetCompanyRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *GetCompanyRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *GetCompanyRequest) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

type GetCompanyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyUuid   string                 `protobuf:"bytes,1,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyResponse) Reset() {
	*x = GetCompanyResponse{}
	mi := &file_company_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyResponse) ProtoMessage() {}

func (x *GetCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyResponse.ProtoReflect.Descriptor instead.
func (*GetCompanyResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{5}
}

func (x *GetCompanyResponse) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

func (x *GetCompanyResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetCompanyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetCompanies
type GetCompaniesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompaniesRequest) Reset() {
	*x = GetCompaniesRequest{}
	mi := &file_company_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompaniesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompaniesRequest) ProtoMessage() {}

func (x *GetCompaniesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompaniesRequest.ProtoReflect.Descriptor instead.
func (*GetCompaniesRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{6}
}

func (x *GetCompaniesRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *GetCompaniesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetCompaniesRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetCompaniesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Companies     []*Company             `protobuf:"bytes,1,rep,name=companies,proto3" json:"companies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompaniesResponse) Reset() {
	*x = GetCompaniesResponse{}
	mi := &file_company_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompaniesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompaniesResponse) ProtoMessage() {}

func (x *GetCompaniesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompaniesResponse.ProtoReflect.Descriptor instead.
func (*GetCompaniesResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{7}
}

func (x *GetCompaniesResponse) GetCompanies() []*Company {
	if x != nil {
		return x.Companies
	}
	return nil
}

type Company struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyUuid   string                 `protobuf:"bytes,1,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_company_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{8}
}

func (x *Company) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

func (x *Company) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Company) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// UpdateCompanyTitle
type UpdateCompanyTitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CompanyUuid   string                 `protobuf:"bytes,3,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCompanyTitleRequest) Reset() {
	*x = UpdateCompanyTitleRequest{}
	mi := &file_company_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompanyTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompanyTitleRequest) ProtoMessage() {}

func (x *UpdateCompanyTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompanyTitleRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompanyTitleRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCompanyTitleRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *UpdateCompanyTitleRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *UpdateCompanyTitleRequest) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

func (x *UpdateCompanyTitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// UpdateCompanyStatus
type UpdateCompanyStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CompanyUuid   string                 `protobuf:"bytes,3,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCompanyStatusRequest) Reset() {
	*x = UpdateCompanyStatusRequest{}
	mi := &file_company_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompanyStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompanyStatusRequest) ProtoMessage() {}

func (x *UpdateCompanyStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompanyStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompanyStatusRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCompanyStatusRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *UpdateCompanyStatusRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *UpdateCompanyStatusRequest) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

func (x *UpdateCompanyStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// DeleteCompany
type DeleteCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CompanyUuid   string                 `protobuf:"bytes,3,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCompanyRequest) Reset() {
	*x = DeleteCompanyRequest{}
	mi := &file_company_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCompanyRequest) ProtoMessage() {}

func (x *DeleteCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCompanyRequest.ProtoReflect.Descriptor instead.
func (*DeleteCompanyRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteCompanyRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *DeleteCompanyRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *DeleteCompanyRequest) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

// CreateCompanyJoinCode
type CreateCompanyJoinCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CompanyUuid   string                 `protobuf:"bytes,3,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	CodeTtl       int64                  `protobuf:"varint,4,opt,name=code_ttl,json=codeTtl,proto3" json:"code_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompanyJoinCodeRequest) Reset() {
	*x = CreateCompanyJoinCodeRequest{}
	mi := &file_company_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompanyJoinCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompanyJoinCodeRequest) ProtoMessage() {}

func (x *CreateCompanyJoinCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompanyJoinCodeRequest.ProtoReflect.Descriptor instead.
func (*CreateCompanyJoinCodeRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{12}
}

func (x *CreateCompanyJoinCodeRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *CreateCompanyJoinCodeRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *CreateCompanyJoinCodeRequest) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

func (x *CreateCompanyJoinCodeRequest) GetCodeTtl() int64 {
	if x != nil {
		return x.CodeTtl
	}
	return 0
}

type CreateCompanyJoinCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JoinCode      string                 `protobuf:"bytes,1,opt,name=join_code,json=joinCode,proto3" json:"join_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompanyJoinCodeResponse) Reset() {
	*x = CreateCompanyJoinCodeResponse{}
	mi := &file_company_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompanyJoinCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompanyJoinCodeResponse) ProtoMessage() {}

func (x *CreateCompanyJoinCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompanyJoinCodeResponse.ProtoReflect.Descriptor instead.
func (*CreateCompanyJoinCodeResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{13}
}

func (x *CreateCompanyJoinCodeResponse) GetJoinCode() string {
	if x != nil {
		return x.JoinCode
	}
	return ""
}

// GetCompanyJoinCodes
type GetCompanyJoinCodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CompanyUuid   string                 `protobuf:"bytes,3,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyJoinCodesRequest) Reset() {
	*x = GetCompanyJoinCodesRequest{}
	mi := &file_company_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyJoinCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyJoinCodesRequest) ProtoMessage() {}

func (x *GetCompanyJoinCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyJoinCodesRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyJoinCodesRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{14}
}

func (x *GetCompanyJoinCodesRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *GetCompanyJoinCodesRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *GetCompanyJoinCodesRequest) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

type GetCompanyJoinCodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codes         []string               `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyJoinCodesResponse) Reset() {
	*x = GetCompanyJoinCodesResponse{}
	mi := &file_company_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyJoinCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyJoinCodesResponse) ProtoMessage() {}

func (x *GetCompanyJoinCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyJoinCodesResponse.ProtoReflect.Descriptor instead.
func (*GetCompanyJoinCodesResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{15}
}

func (x *GetCompanyJoinCodesResponse) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

// DeleteCompanyJoinCodes
type DeleteCompanyJoinCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CompanyUuid   string                 `protobuf:"bytes,3,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCompanyJoinCodeRequest) Reset() {
	*x = DeleteCompanyJoinCodeRequest{}
	mi := &file_company_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCompanyJoinCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCompanyJoinCodeRequest) ProtoMessage() {}

func (x *DeleteCompanyJoinCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCompanyJoinCodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteCompanyJoinCodeRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteCompanyJoinCodeRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *DeleteCompanyJoinCodeRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *DeleteCompanyJoinCodeRequest) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

func (x *DeleteCompanyJoinCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// JoinCompany
type JoinCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	JoinCode      string                 `protobuf:"bytes,3,opt,name=join_code,json=joinCode,proto3" json:"join_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinCompanyRequest) Reset() {
	*x = JoinCompanyRequest{}
	mi := &file_company_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCompanyRequest) ProtoMessage() {}

func (x *JoinCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCompanyRequest.ProtoReflect.Descriptor instead.
func (*JoinCompanyRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{17}
}

func (x *JoinCompanyRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *JoinCompanyRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *JoinCompanyRequest) GetJoinCode() string {
	if x != nil {
		return x.JoinCode
	}
	return ""
}

type JoinCompanyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyUuid   string                 `protobuf:"bytes,1,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinCompanyResponse) Reset() {
	*x = JoinCompanyResponse{}
	mi := &file_company_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCompanyResponse) ProtoMessage() {}

func (x *JoinCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCompanyResponse.ProtoReflect.Descriptor instead.
func (*JoinCompanyResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{18}
}

func (x *JoinCompanyResponse) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

func (x *JoinCompanyResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// GetCompanyEmployee
type GetCompanyEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	InitiatorUuid string                 `protobuf:"bytes,2,opt,name=initiator_uuid,json=initiatorUuid,proto3" json:"initiator_uuid,omitempty"`
	TargetUuid    string                 `protobuf:"bytes,3,opt,name=target_uuid,json=targetUuid,proto3" json:"target_uuid,omitempty"`
	CompanyUuid   string                 `protobuf:"bytes,4,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyEmployeeRequest) Reset() {
	*x = GetCompanyEmployeeRequest{}
	mi := &file_company_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyEmployeeRequest) ProtoMessage() {}

func (x *GetCompanyEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyEmployeeRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{19}
}

func (x *GetCompanyEmployeeRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *GetCompanyEmployeeRequest) GetInitiatorUuid() string {
	if x != nil {
		return x.InitiatorUuid
	}
	return ""
}

func (x *GetCompanyEmployeeRequest) GetTargetUuid() string {
	if x != nil {
		return x.TargetUuid
	}
	return ""
}

func (x *GetCompanyEmployeeRequest) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

type GetCompanyEmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	JoinedAt      string                 `protobuf:"bytes,2,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyEmployeeResponse) Reset() {
	*x = GetCompanyEmployeeResponse{}
	mi := &file_company_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyEmployeeResponse) ProtoMessage() {}

func (x *GetCompanyEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyEmployeeResponse.ProtoReflect.Descriptor instead.
func (*GetCompanyEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{20}
}

func (x *GetCompanyEmployeeResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetCompanyEmployeeResponse) GetJoinedAt() string {
	if x != nil {
		return x.JoinedAt
	}
	return ""
}

// GetCompanyEmployees
type GetCompanyEmployeesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CompanyUuid   string                 `protobuf:"bytes,3,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Count         int64                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Offset        int64                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyEmployeesRequest) Reset() {
	*x = GetCompanyEmployeesRequest{}
	mi := &file_company_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyEmployeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyEmployeesRequest) ProtoMessage() {}

func (x *GetCompanyEmployeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyEmployeesRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyEmployeesRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{21}
}

func (x *GetCompanyEmployeesRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *GetCompanyEmployeesRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *GetCompanyEmployeesRequest) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

func (x *GetCompanyEmployeesRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetCompanyEmployeesRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetCompanyEmployeesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetCompanyEmployeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employees     []*Employee            `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyEmployeesResponse) Reset() {
	*x = GetCompanyEmployeesResponse{}
	mi := &file_company_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyEmployeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyEmployeesResponse) ProtoMessage() {}

func (x *GetCompanyEmployeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyEmployeesResponse.ProtoReflect.Descriptor instead.
func (*GetCompanyEmployeesResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{22}
}

func (x *GetCompanyEmployeesResponse) GetEmployees() []*Employee {
	if x != nil {
		return x.Employees
	}
	return nil
}

type Employee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	JoinedAt      string                 `protobuf:"bytes,3,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Employee) Reset() {
	*x = Employee{}
	mi := &file_company_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{23}
}

func (x *Employee) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *Employee) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Employee) GetJoinedAt() string {
	if x != nil {
		return x.JoinedAt
	}
	return ""
}

// GetCompanyEmployeesSummary
type GetCompanyEmployeesSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CompanyUuid   string                 `protobuf:"bytes,3,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyEmployeesSummaryRequest) Reset() {
	*x = GetCompanyEmployeesSummaryRequest{}
	mi := &file_company_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyEmployeesSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyEmployeesSummaryRequest) ProtoMessage() {}

func (x *GetCompanyEmployeesSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyEmployeesSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyEmployeesSummaryRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{24}
}

func (x *GetCompanyEmployeesSummaryRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *GetCompanyEmployeesSummaryRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *GetCompanyEmployeesSummaryRequest) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

type GetCompanyEmployeesSummaryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChiefCount      int64                  `protobuf:"varint,1,opt,name=chief_count,json=chiefCount,proto3" json:"chief_count,omitempty"`
	AnalyticsCount  int64                  `protobuf:"varint,2,opt,name=analytics_count,json=analyticsCount,proto3" json:"analytics_count,omitempty"`
	ManagerCount    int64                  `protobuf:"varint,3,opt,name=manager_count,json=managerCount,proto3" json:"manager_count,omitempty"`
	EngineerCount   int64                  `protobuf:"varint,4,opt,name=engineer_count,json=engineerCount,proto3" json:"engineer_count,omitempty"`
	UnemployedCount int64                  `protobuf:"varint,5,opt,name=unemployed_count,json=unemployedCount,proto3" json:"unemployed_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCompanyEmployeesSummaryResponse) Reset() {
	*x = GetCompanyEmployeesSummaryResponse{}
	mi := &file_company_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyEmployeesSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyEmployeesSummaryResponse) ProtoMessage() {}

func (x *GetCompanyEmployeesSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyEmployeesSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetCompanyEmployeesSummaryResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{25}
}

func (x *GetCompanyEmployeesSummaryResponse) GetChiefCount() int64 {
	if x != nil {
		return x.ChiefCount
	}
	return 0
}

func (x *GetCompanyEmployeesSummaryResponse) GetAnalyticsCount() int64 {
	if x != nil {
		return x.AnalyticsCount
	}
	return 0
}

func (x *GetCompanyEmployeesSummaryResponse) GetManagerCount() int64 {
	if x != nil {
		return x.ManagerCount
	}
	return 0
}

func (x *GetCompanyEmployeesSummaryResponse) GetEngineerCount() int64 {
	if x != nil {
		return x.EngineerCount
	}
	return 0
}

func (x *GetCompanyEmployeesSummaryResponse) GetUnemployedCount() int64 {
	if x != nil {
		return x.UnemployedCount
	}
	return 0
}

// UpdateEmployeeRole
type UpdateEmployeeRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	InitiatorUuid string                 `protobuf:"bytes,2,opt,name=initiator_uuid,json=initiatorUuid,proto3" json:"initiator_uuid,omitempty"`
	TargetUuid    string                 `protobuf:"bytes,3,opt,name=target_uuid,json=targetUuid,proto3" json:"target_uuid,omitempty"`
	CompanyUuid   string                 `protobuf:"bytes,4,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmployeeRoleRequest) Reset() {
	*x = UpdateEmployeeRoleRequest{}
	mi := &file_company_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmployeeRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmployeeRoleRequest) ProtoMessage() {}

func (x *UpdateEmployeeRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmployeeRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmployeeRoleRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateEmployeeRoleRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *UpdateEmployeeRoleRequest) GetInitiatorUuid() string {
	if x != nil {
		return x.InitiatorUuid
	}
	return ""
}

func (x *UpdateEmployeeRoleRequest) GetTargetUuid() string {
	if x != nil {
		return x.TargetUuid
	}
	return ""
}

func (x *UpdateEmployeeRoleRequest) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

func (x *UpdateEmployeeRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// RemoveCompanyEmployee
type RemoveCompanyEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	InitiatorUuid string                 `protobuf:"bytes,2,opt,name=initiator_uuid,json=initiatorUuid,proto3" json:"initiator_uuid,omitempty"`
	CompanyUuid   string                 `protobuf:"bytes,3,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	TargetUuid    string                 `protobuf:"bytes,4,opt,name=target_uuid,json=targetUuid,proto3" json:"target_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCompanyEmployeeRequest) Reset() {
	*x = RemoveCompanyEmployeeRequest{}
	mi := &file_company_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCompanyEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCompanyEmployeeRequest) ProtoMessage() {}

func (x *RemoveCompanyEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCompanyEmployeeRequest.ProtoReflect.Descriptor instead.
func (*RemoveCompanyEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{27}
}

func (x *RemoveCompanyEmployeeRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *RemoveCompanyEmployeeRequest) GetInitiatorUuid() string {
	if x != nil {
		return x.InitiatorUuid
	}
	return ""
}

func (x *RemoveCompanyEmployeeRequest) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

func (x *RemoveCompanyEmployeeRequest) GetTargetUuid() string {
	if x != nil {
		return x.TargetUuid
	}
	return ""
}

var File_company_proto protoreflect.FileDescriptor

const file_company_proto_rawDesc = "" +
	"\n" +
	"\rcompany.proto\x12\acompany\x1a\x1bgoogle/protobuf/empty.proto\"2\n" +
	"\rHealthRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06health\x18\x01 \x01(\tR\x06health\"l\n" +
	"\x14CreateCompanyRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\":\n" +
	"\x15CreateCompanyResponse\x12!\n" +
	"\fcompany_uuid\x18\x01 \x01(\tR\vcompanyUuid\"v\n" +
	"\x11GetCompanyRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12!\n" +
	"\fcompany_uuid\x18\x03 \x01(\tR\vcompanyUuid\"e\n" +
	"\x12GetCompanyResponse\x12!\n" +
	"\fcompany_uuid\x18\x01 \x01(\tR\vcompanyUuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"f\n" +
	"\x13GetCompaniesRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"F\n" +
	"\x14GetCompaniesResponse\x12.\n" +
	"\tcompanies\x18\x01 \x03(\v2\x10.company.CompanyR\tcompanies\"Z\n" +
	"\aCompany\x12!\n" +
	"\fcompany_uuid\x18\x01 \x01(\tR\vcompanyUuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x94\x01\n" +
	"\x19UpdateCompanyTitleRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12!\n" +
	"\fcompany_uuid\x18\x03 \x01(\tR\vcompanyUuid\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"\x97\x01\n" +
	"\x1aUpdateCompanyStatusRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12!\n" +
	"\fcompany_uuid\x18\x03 \x01(\tR\vcompanyUuid\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"y\n" +
	"\x14DeleteCompanyRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12!\n" +
	"\fcompany_uuid\x18\x03 \x01(\tR\vcompanyUuid\"\x9c\x01\n" +
	"\x1cCreateCompanyJoinCodeRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12!\n" +
	"\fcompany_uuid\x18\x03 \x01(\tR\vcompanyUuid\x12\x19\n" +
	"\bcode_ttl\x18\x04 \x01(\x03R\acodeTtl\"<\n" +
	"\x1dCreateCompanyJoinCodeResponse\x12\x1b\n" +
	"\tjoin_code\x18\x01 \x01(\tR\bjoinCode\"\x7f\n" +
	"\x1aGetCompanyJoinCodesRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12!\n" +
	"\fcompany_uuid\x18\x03 \x01(\tR\vcompanyUuid\"3\n" +
	"\x1bGetCompanyJoinCodesResponse\x12\x14\n" +
	"\x05codes\x18\x01 \x03(\tR\x05codes\"\x95\x01\n" +
	"\x1cDeleteCompanyJoinCodeRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12!\n" +
	"\fcompany_uuid\x18\x03 \x01(\tR\vcompanyUuid\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\"q\n" +
	"\x12JoinCompanyRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12\x1b\n" +
	"\tjoin_code\x18\x03 \x01(\tR\bjoinCode\"L\n" +
	"\x13JoinCompanyResponse\x12!\n" +
	"\fcompany_uuid\x18\x01 \x01(\tR\vcompanyUuid\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"\xa9\x01\n" +
	"\x19GetCompanyEmployeeRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12%\n" +
	"\x0einitiator_uuid\x18\x02 \x01(\tR\rinitiatorUuid\x12\x1f\n" +
	"\vtarget_uuid\x18\x03 \x01(\tR\n" +
	"targetUuid\x12!\n" +
	"\fcompany_uuid\x18\x04 \x01(\tR\vcompanyUuid\"M\n" +
	"\x1aGetCompanyEmployeeResponse\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x1b\n" +
	"\tjoined_at\x18\x02 \x01(\tR\bjoinedAt\"\xc1\x01\n" +
	"\x1aGetCompanyEmployeesRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12!\n" +
	"\fcompany_uuid\x18\x03 \x01(\tR\vcompanyUuid\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x03R\x05count\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x03R\x06offset\"N\n" +
	"\x1bGetCompanyEmployeesResponse\x12/\n" +
	"\temployees\x18\x01 \x03(\v2\x11.company.EmployeeR\temployees\"X\n" +
	"\bEmployee\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1b\n" +
	"\tjoined_at\x18\x03 \x01(\tR\bjoinedAt\"\x86\x01\n" +
	"!GetCompanyEmployeesSummaryRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12!\n" +
	"\fcompany_uuid\x18\x03 \x01(\tR\vcompanyUuid\"\xe5\x01\n" +
	"\"GetCompanyEmployeesSummaryResponse\x12\x1f\n" +
	"\vchief_count\x18\x01 \x01(\x03R\n" +
	"chiefCount\x12'\n" +
	"\x0fanalytics_count\x18\x02 \x01(\x03R\x0eanalyticsCount\x12#\n" +
	"\rmanager_count\x18\x03 \x01(\x03R\fmanagerCount\x12%\n" +
	"\x0eengineer_count\x18\x04 \x01(\x03R\rengineerCount\x12)\n" +
	"\x10unemployed_count\x18\x05 \x01(\x03R\x0funemployedCount\"\xbd\x01\n" +
	"\x19UpdateEmployeeRoleRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12%\n" +
	"\x0einitiator_uuid\x18\x02 \x01(\tR\rinitiatorUuid\x12\x1f\n" +
	"\vtarget_uuid\x18\x03 \x01(\tR\n" +
	"targetUuid\x12!\n" +
	"\fcompany_uuid\x18\x04 \x01(\tR\vcompanyUuid\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"\xac\x01\n" +
	"\x1cRemoveCompanyEmployeeRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12%\n" +
	"\x0einitiator_uuid\x18\x02 \x01(\tR\rinitiatorUuid\x12!\n" +
	"\fcompany_uuid\x18\x03 \x01(\tR\vcompanyUuid\x12\x1f\n" +
	"\vtarget_uuid\x18\x04 \x01(\tR\n" +
	"targetUuid2\xeb\n" +
	"\n" +
	"\x0eCompanyService\x129\n" +
	"\x06Health\x12\x16.company.HealthRequest\x1a\x17.company.HealthResponse\x12N\n" +
	"\rCreateCompany\x12\x1d.company.CreateCompanyRequest\x1a\x1e.company.CreateCompanyResponse\x12E\n" +
	"\n" +
	"GetCompany\x12\x1a.company.GetCompanyRequest\x1a\x1b.company.GetCompanyResponse\x12K\n" +
	"\fGetCompanies\x12\x1c.company.GetCompaniesRequest\x1a\x1d.company.GetCompaniesResponse\x12P\n" +
	"\x12UpdateCompanyTitle\x12\".company.UpdateCompanyTitleRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\x13UpdateCompanyStatus\x12#.company.UpdateCompanyStatusRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\rDeleteCompany\x12\x1d.company.DeleteCompanyRequest\x1a\x16.google.protobuf.Empty\x12f\n" +
	"\x15CreateCompanyJoinCode\x12%.company.CreateCompanyJoinCodeRequest\x1a&.company.CreateCompanyJoinCodeResponse\x12`\n" +
	"\x13GetCompanyJoinCodes\x12#.company.GetCompanyJoinCodesRequest\x1a$.company.GetCompanyJoinCodesResponse\x12V\n" +
	"\x15DeleteCompanyJoinCode\x12%.company.DeleteCompanyJoinCodeRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\vJoinCompany\x12\x1b.company.JoinCompanyRequest\x1a\x1c.company.JoinCompanyResponse\x12]\n" +
	"\x12GetCompanyEmployee\x12\".company.GetCompanyEmployeeRequest\x1a#.company.GetCompanyEmployeeResponse\x12`\n" +
	"\x13GetCompanyEmployees\x12#.company.GetCompanyEmployeesRequest\x1a$.company.GetCompanyEmployeesResponse\x12u\n" +
	"\x1aGetCompanyEmployeesSummary\x12*.company.GetCompanyEmployeesSummaryRequest\x1a+.company.GetCompanyEmployeesSummaryResponse\x12P\n" +
	"\x12UpdateEmployeeRole\x12\".company.UpdateEmployeeRoleRequest\x1a\x16.google.protobuf.Empty\x12V\n" +
	"\x15RemoveCompanyEmployee\x12%.company.RemoveCompanyEmployeeRequest\x1a\x16.google.protobuf.EmptyB\x15Z\x13proto/company_protob\x06proto3"

var (
	file_company_proto_rawDescOnce sync.Once
	file_company_proto_rawDescData []byte
)

func file_company_proto_rawDescGZIP() []byte {
	file_company_proto_rawDescOnce.Do(func() {
		file_company_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_company_proto_rawDesc), len(file_company_proto_rawDesc)))
	})
	return file_company_proto_rawDescData
}

var file_company_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_company_proto_goTypes = []any{
	(*HealthRequest)(nil),                      // 0: company.HealthRequest
	(*HealthResponse)(nil),                     // 1: company.HealthResponse
	(*CreateCompanyRequest)(nil),               // 2: company.CreateCompanyRequest
	(*CreateCompanyResponse)(nil),              // 3: company.CreateCompanyResponse
	(*GetCompanyRequest)(nil),                  // 4: company.GetCompanyRequest
	(*GetCompanyResponse)(nil),                 // 5: company.GetCompanyResponse
	(*GetCompaniesRequest)(nil),                // 6: company.GetCompaniesRequest
	(*GetCompaniesResponse)(nil),               // 7: company.GetCompaniesResponse
	(*Company)(nil),                            // 8: company.Company
	(*UpdateCompanyTitleRequest)(nil),          // 9: company.UpdateCompanyTitleRequest
	(*UpdateCompanyStatusRequest)(nil),         // 10: company.UpdateCompanyStatusRequest
	(*DeleteCompanyRequest)(nil),               // 11: company.DeleteCompanyRequest
	(*CreateCompanyJoinCodeRequest)(nil),       // 12: company.CreateCompanyJoinCodeRequest
	(*CreateCompanyJoinCodeResponse)(nil),      // 13: company.CreateCompanyJoinCodeResponse
	(*GetCompanyJoinCodesRequest)(nil),         // 14: company.GetCompanyJoinCodesRequest
	(*GetCompanyJoinCodesResponse)(nil),        // 15: company.GetCompanyJoinCodesResponse
	(*DeleteCompanyJoinCodeRequest)(nil),       // 16: company.DeleteCompanyJoinCodeRequest
	(*JoinCompanyRequest)(nil),                 // 17: company.JoinCompanyRequest
	(*JoinCompanyResponse)(nil),                // 18: company.JoinCompanyResponse
	(*GetCompanyEmployeeRequest)(nil),          // 19: company.GetCompanyEmployeeRequest
	(*GetCompanyEmployeeResponse)(nil),         // 20: company.GetCompanyEmployeeResponse
	(*GetCompanyEmployeesRequest)(nil),         // 21: company.GetCompanyEmployeesRequest
	(*GetCompanyEmployeesResponse)(nil),        // 22: company.GetCompanyEmployeesResponse
	(*Employee)(nil),                           // 23: company.Employee
	(*GetCompanyEmployeesSummaryRequest)(nil),  // 24: company.GetCompanyEmployeesSummaryRequest
	(*GetCompanyEmployeesSummaryResponse)(nil), // 25: company.GetCompanyEmployeesSummaryResponse
	(*UpdateEmployeeRoleRequest)(nil),          // 26: company.UpdateEmployeeRoleRequest
	(*RemoveCompanyEmployeeRequest)(nil),       // 27: company.RemoveCompanyEmployeeRequest
	(*emptypb.Empty)(nil),                      // 28: google.protobuf.Empty
}
var file_company_proto_depIdxs = []int32{
	8,  // 0: company.GetCompaniesResponse.companies:type_name -> company.Company
	23, // 1: company.GetCompanyEmployeesResponse.employees:type_name -> company.Employee
	0,  // 2: company.CompanyService.Health:input_type -> company.HealthRequest
	2,  // 3: company.CompanyService.CreateCompany:input_type -> company.CreateCompanyRequest
	4,  // 4: company.CompanyService.GetCompany:input_type -> company.GetCompanyRequest
	6,  // 5: company.CompanyService.GetCompanies:input_type -> company.GetCompaniesRequest
	9,  // 6: company.CompanyService.UpdateCompanyTitle:input_type -> company.UpdateCompanyTitleRequest
	10, // 7: company.CompanyService.UpdateCompanyStatus:input_type -> company.UpdateCompanyStatusRequest
	11, // 8: company.CompanyService.DeleteCompany:input_type -> company.DeleteCompanyRequest
	12, // 9: company.CompanyService.CreateCompanyJoinCode:input_type -> company.CreateCompanyJoinCodeRequest
	14, // 10: company.CompanyService.GetCompanyJoinCodes:input_type -> company.GetCompanyJoinCodesRequest
	16, // 11: company.CompanyService.DeleteCompanyJoinCode:input_type -> company.DeleteCompanyJoinCodeRequest
	17, // 12: company.CompanyService.JoinCompany:input_type -> company.JoinCompanyRequest
	19, // 13: company.CompanyService.GetCompanyEmployee:input_type -> company.GetCompanyEmployeeRequest
	21, // 14: company.CompanyService.GetCompanyEmployees:input_type -> company.GetCompanyEmployeesRequest
	24, // 15: company.CompanyService.GetCompanyEmployeesSummary:input_type -> company.GetCompanyEmployeesSummaryRequest
	26, // 16: company.CompanyService.UpdateEmployeeRole:input_type -> company.UpdateEmployeeRoleRequest
	27, // 17: company.CompanyService.RemoveCompanyEmployee:input_type -> company.RemoveCompanyEmployeeRequest
	1,  // 18: company.CompanyService.Health:output_type -> company.HealthResponse
	3,  // 19: company.CompanyService.CreateCompany:output_type -> company.CreateCompanyResponse
	5,  // 20: company.CompanyService.GetCompany:output_type -> company.GetCompanyResponse
	7,  // 21: company.CompanyService.GetCompanies:output_type -> company.GetCompaniesResponse
	28, // 22: company.CompanyService.UpdateCompanyTitle:output_type -> google.protobuf.Empty
	28, // 23: company.CompanyService.UpdateCompanyStatus:output_type -> google.protobuf.Empty
	28, // 24: company.CompanyService.DeleteCompany:output_type -> google.protobuf.Empty
	13, // 25: company.CompanyService.CreateCompanyJoinCode:output_type -> company.CreateCompanyJoinCodeResponse
	15, // 26: company.CompanyService.GetCompanyJoinCodes:output_type -> company.GetCompanyJoinCodesResponse
	28, // 27: company.CompanyService.DeleteCompanyJoinCode:output_type -> google.protobuf.Empty
	18, // 28: company.CompanyService.JoinCompany:output_type -> company.JoinCompanyResponse
	20, // 29: company.CompanyService.GetCompanyEmployee:output_type -> company.GetCompanyEmployeeResponse
	22, // 30: company.CompanyService.GetCompanyEmployees:output_type -> company.GetCompanyEmployeesResponse
	25, // 31: company.CompanyService.GetCompanyEmployeesSummary:output_type -> company.GetCompanyEmployeesSummaryResponse
	28, // 32: company.CompanyService.UpdateEmployeeRole:output_type -> google.protobuf.Empty
	28, // 33: company.CompanyService.RemoveCompanyEmployee:output_type -> google.protobuf.Empty
	18, // [18:34] is the sub-list for method output_type
	2,  // [2:18] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_company_proto_init() }
func file_company_proto_init() {
	if File_company_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_company_proto_rawDesc), len(file_company_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_company_proto_goTypes,
		DependencyIndexes: file_company_proto_depIdxs,
		MessageInfos:      file_company_proto_msgTypes,
	}.Build()
	File_company_proto = out.File
	file_company_proto_goTypes = nil
	file_company_proto_depIdxs = nil
}
