// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: company.proto

package company_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Health
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_company_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{0}
}

func (x *HealthRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        string                 `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_company_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

// CreateCompany
type CreateCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompanyRequest) Reset() {
	*x = CreateCompanyRequest{}
	mi := &file_company_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompanyRequest) ProtoMessage() {}

func (x *CreateCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompanyRequest.ProtoReflect.Descriptor instead.
func (*CreateCompanyRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCompanyRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *CreateCompanyRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *CreateCompanyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateCompanyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyUuid   string                 `protobuf:"bytes,1,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompanyResponse) Reset() {
	*x = CreateCompanyResponse{}
	mi := &file_company_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompanyResponse) ProtoMessage() {}

func (x *CreateCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompanyResponse.ProtoReflect.Descriptor instead.
func (*CreateCompanyResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCompanyResponse) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

// GetCompany
type GetCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CompanyUuid   string                 `protobuf:"bytes,3,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyRequest) Reset() {
	*x = GetCompanyRequest{}
	mi := &file_company_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyRequest) ProtoMessage() {}

func (x *GetCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{4}
}

func (x *GetCompanyRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *GetCompanyRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *GetCompanyRequest) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

type GetCompanyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyUuid   string                 `protobuf:"bytes,1,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyResponse) Reset() {
	*x = GetCompanyResponse{}
	mi := &file_company_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyResponse) ProtoMessage() {}

func (x *GetCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyResponse.ProtoReflect.Descriptor instead.
func (*GetCompanyResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{5}
}

func (x *GetCompanyResponse) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

func (x *GetCompanyResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetCompanyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetCompanies
type GetCompaniesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompaniesRequest) Reset() {
	*x = GetCompaniesRequest{}
	mi := &file_company_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompaniesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompaniesRequest) ProtoMessage() {}

func (x *GetCompaniesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompaniesRequest.ProtoReflect.Descriptor instead.
func (*GetCompaniesRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{6}
}

func (x *GetCompaniesRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *GetCompaniesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetCompaniesRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetCompaniesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Companies     []*Company             `protobuf:"bytes,1,rep,name=companies,proto3" json:"companies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompaniesResponse) Reset() {
	*x = GetCompaniesResponse{}
	mi := &file_company_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompaniesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompaniesResponse) ProtoMessage() {}

func (x *GetCompaniesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompaniesResponse.ProtoReflect.Descriptor instead.
func (*GetCompaniesResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{7}
}

func (x *GetCompaniesResponse) GetCompanies() []*Company {
	if x != nil {
		return x.Companies
	}
	return nil
}

type Company struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyUuid   string                 `protobuf:"bytes,1,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_company_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{8}
}

func (x *Company) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

func (x *Company) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Company) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// UpdateCompanyTitle
type UpdateCompanyTitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CompanyUuid   string                 `protobuf:"bytes,3,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCompanyTitleRequest) Reset() {
	*x = UpdateCompanyTitleRequest{}
	mi := &file_company_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompanyTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompanyTitleRequest) ProtoMessage() {}

func (x *UpdateCompanyTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompanyTitleRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompanyTitleRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCompanyTitleRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *UpdateCompanyTitleRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *UpdateCompanyTitleRequest) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

func (x *UpdateCompanyTitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// UpdateCompanyStatus
type UpdateCompanyStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CompanyUuid   string                 `protobuf:"bytes,3,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCompanyStatusRequest) Reset() {
	*x = UpdateCompanyStatusRequest{}
	mi := &file_company_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompanyStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompanyStatusRequest) ProtoMessage() {}

func (x *UpdateCompanyStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompanyStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompanyStatusRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCompanyStatusRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *UpdateCompanyStatusRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *UpdateCompanyStatusRequest) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

func (x *UpdateCompanyStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// DeleteCompany
type DeleteCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CompanyUuid   string                 `protobuf:"bytes,3,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCompanyRequest) Reset() {
	*x = DeleteCompanyRequest{}
	mi := &file_company_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCompanyRequest) ProtoMessage() {}

func (x *DeleteCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCompanyRequest.ProtoReflect.Descriptor instead.
func (*DeleteCompanyRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteCompanyRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *DeleteCompanyRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *DeleteCompanyRequest) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

// GenerateJoinCompanyCode
type GenerateJoinCompanyCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CompanyUuid   string                 `protobuf:"bytes,3,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateJoinCompanyCodeRequest) Reset() {
	*x = GenerateJoinCompanyCodeRequest{}
	mi := &file_company_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateJoinCompanyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateJoinCompanyCodeRequest) ProtoMessage() {}

func (x *GenerateJoinCompanyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateJoinCompanyCodeRequest.ProtoReflect.Descriptor instead.
func (*GenerateJoinCompanyCodeRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{12}
}

func (x *GenerateJoinCompanyCodeRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *GenerateJoinCompanyCodeRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *GenerateJoinCompanyCodeRequest) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

type GenerateJoinCompanyCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JoinCode      string                 `protobuf:"bytes,1,opt,name=join_code,json=joinCode,proto3" json:"join_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateJoinCompanyCodeResponse) Reset() {
	*x = GenerateJoinCompanyCodeResponse{}
	mi := &file_company_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateJoinCompanyCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateJoinCompanyCodeResponse) ProtoMessage() {}

func (x *GenerateJoinCompanyCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateJoinCompanyCodeResponse.ProtoReflect.Descriptor instead.
func (*GenerateJoinCompanyCodeResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{13}
}

func (x *GenerateJoinCompanyCodeResponse) GetJoinCode() string {
	if x != nil {
		return x.JoinCode
	}
	return ""
}

// JoinCompany
type JoinCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	JoinCode      string                 `protobuf:"bytes,3,opt,name=join_code,json=joinCode,proto3" json:"join_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinCompanyRequest) Reset() {
	*x = JoinCompanyRequest{}
	mi := &file_company_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCompanyRequest) ProtoMessage() {}

func (x *JoinCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCompanyRequest.ProtoReflect.Descriptor instead.
func (*JoinCompanyRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{14}
}

func (x *JoinCompanyRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *JoinCompanyRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *JoinCompanyRequest) GetJoinCode() string {
	if x != nil {
		return x.JoinCode
	}
	return ""
}

type JoinCompanyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyUuid   string                 `protobuf:"bytes,1,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinCompanyResponse) Reset() {
	*x = JoinCompanyResponse{}
	mi := &file_company_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCompanyResponse) ProtoMessage() {}

func (x *JoinCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCompanyResponse.ProtoReflect.Descriptor instead.
func (*JoinCompanyResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{15}
}

func (x *JoinCompanyResponse) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

func (x *JoinCompanyResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// GetCompanyEmployees
type GetCompanyEmployeesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CompanyUuid   string                 `protobuf:"bytes,3,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyEmployeesRequest) Reset() {
	*x = GetCompanyEmployeesRequest{}
	mi := &file_company_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyEmployeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyEmployeesRequest) ProtoMessage() {}

func (x *GetCompanyEmployeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyEmployeesRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyEmployeesRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{16}
}

func (x *GetCompanyEmployeesRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *GetCompanyEmployeesRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *GetCompanyEmployeesRequest) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

type GetCompanyEmployeesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChiefCount     int64                  `protobuf:"varint,1,opt,name=chief_count,json=chiefCount,proto3" json:"chief_count,omitempty"`
	AnalyticsCount int64                  `protobuf:"varint,2,opt,name=analytics_count,json=analyticsCount,proto3" json:"analytics_count,omitempty"`
	ManagerCount   int64                  `protobuf:"varint,3,opt,name=manager_count,json=managerCount,proto3" json:"manager_count,omitempty"`
	EngineerCount  int64                  `protobuf:"varint,4,opt,name=engineer_count,json=engineerCount,proto3" json:"engineer_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCompanyEmployeesResponse) Reset() {
	*x = GetCompanyEmployeesResponse{}
	mi := &file_company_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyEmployeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyEmployeesResponse) ProtoMessage() {}

func (x *GetCompanyEmployeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyEmployeesResponse.ProtoReflect.Descriptor instead.
func (*GetCompanyEmployeesResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{17}
}

func (x *GetCompanyEmployeesResponse) GetChiefCount() int64 {
	if x != nil {
		return x.ChiefCount
	}
	return 0
}

func (x *GetCompanyEmployeesResponse) GetAnalyticsCount() int64 {
	if x != nil {
		return x.AnalyticsCount
	}
	return 0
}

func (x *GetCompanyEmployeesResponse) GetManagerCount() int64 {
	if x != nil {
		return x.ManagerCount
	}
	return 0
}

func (x *GetCompanyEmployeesResponse) GetEngineerCount() int64 {
	if x != nil {
		return x.EngineerCount
	}
	return 0
}

// RemoveCompanyEmployee
type RemoveCompanyEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	InitiatorUuid string                 `protobuf:"bytes,2,opt,name=initiator_uuid,json=initiatorUuid,proto3" json:"initiator_uuid,omitempty"`
	CompanyUuid   string                 `protobuf:"bytes,3,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	TargetUuid    string                 `protobuf:"bytes,4,opt,name=target_uuid,json=targetUuid,proto3" json:"target_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCompanyEmployeeRequest) Reset() {
	*x = RemoveCompanyEmployeeRequest{}
	mi := &file_company_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCompanyEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCompanyEmployeeRequest) ProtoMessage() {}

func (x *RemoveCompanyEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCompanyEmployeeRequest.ProtoReflect.Descriptor instead.
func (*RemoveCompanyEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveCompanyEmployeeRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *RemoveCompanyEmployeeRequest) GetInitiatorUuid() string {
	if x != nil {
		return x.InitiatorUuid
	}
	return ""
}

func (x *RemoveCompanyEmployeeRequest) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

func (x *RemoveCompanyEmployeeRequest) GetTargetUuid() string {
	if x != nil {
		return x.TargetUuid
	}
	return ""
}

var File_company_proto protoreflect.FileDescriptor

const file_company_proto_rawDesc = "" +
	"\n" +
	"\rcompany.proto\x12\acompany\x1a\x1bgoogle/protobuf/empty.proto\"2\n" +
	"\rHealthRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06health\x18\x01 \x01(\tR\x06health\"l\n" +
	"\x14CreateCompanyRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\":\n" +
	"\x15CreateCompanyResponse\x12!\n" +
	"\fcompany_uuid\x18\x01 \x01(\tR\vcompanyUuid\"v\n" +
	"\x11GetCompanyRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12!\n" +
	"\fcompany_uuid\x18\x03 \x01(\tR\vcompanyUuid\"e\n" +
	"\x12GetCompanyResponse\x12!\n" +
	"\fcompany_uuid\x18\x01 \x01(\tR\vcompanyUuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"f\n" +
	"\x13GetCompaniesRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"F\n" +
	"\x14GetCompaniesResponse\x12.\n" +
	"\tcompanies\x18\x01 \x03(\v2\x10.company.CompanyR\tcompanies\"Z\n" +
	"\aCompany\x12!\n" +
	"\fcompany_uuid\x18\x01 \x01(\tR\vcompanyUuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x94\x01\n" +
	"\x19UpdateCompanyTitleRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12!\n" +
	"\fcompany_uuid\x18\x03 \x01(\tR\vcompanyUuid\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"\x97\x01\n" +
	"\x1aUpdateCompanyStatusRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12!\n" +
	"\fcompany_uuid\x18\x03 \x01(\tR\vcompanyUuid\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"y\n" +
	"\x14DeleteCompanyRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12!\n" +
	"\fcompany_uuid\x18\x03 \x01(\tR\vcompanyUuid\"\x83\x01\n" +
	"\x1eGenerateJoinCompanyCodeRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12!\n" +
	"\fcompany_uuid\x18\x03 \x01(\tR\vcompanyUuid\">\n" +
	"\x1fGenerateJoinCompanyCodeResponse\x12\x1b\n" +
	"\tjoin_code\x18\x01 \x01(\tR\bjoinCode\"q\n" +
	"\x12JoinCompanyRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12\x1b\n" +
	"\tjoin_code\x18\x03 \x01(\tR\bjoinCode\"L\n" +
	"\x13JoinCompanyResponse\x12!\n" +
	"\fcompany_uuid\x18\x01 \x01(\tR\vcompanyUuid\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"\x7f\n" +
	"\x1aGetCompanyEmployeesRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12!\n" +
	"\fcompany_uuid\x18\x03 \x01(\tR\vcompanyUuid\"\xb3\x01\n" +
	"\x1bGetCompanyEmployeesResponse\x12\x1f\n" +
	"\vchief_count\x18\x01 \x01(\x03R\n" +
	"chiefCount\x12'\n" +
	"\x0fanalytics_count\x18\x02 \x01(\x03R\x0eanalyticsCount\x12#\n" +
	"\rmanager_count\x18\x03 \x01(\x03R\fmanagerCount\x12%\n" +
	"\x0eengineer_count\x18\x04 \x01(\x03R\rengineerCount\"\xac\x01\n" +
	"\x1cRemoveCompanyEmployeeRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12%\n" +
	"\x0einitiator_uuid\x18\x02 \x01(\tR\rinitiatorUuid\x12!\n" +
	"\fcompany_uuid\x18\x03 \x01(\tR\vcompanyUuid\x12\x1f\n" +
	"\vtarget_uuid\x18\x04 \x01(\tR\n" +
	"targetUuid2\x8f\a\n" +
	"\x0eCompanyService\x129\n" +
	"\x06Health\x12\x16.company.HealthRequest\x1a\x17.company.HealthResponse\x12N\n" +
	"\rCreateCompany\x12\x1d.company.CreateCompanyRequest\x1a\x1e.company.CreateCompanyResponse\x12E\n" +
	"\n" +
	"GetCompany\x12\x1a.company.GetCompanyRequest\x1a\x1b.company.GetCompanyResponse\x12K\n" +
	"\fGetCompanies\x12\x1c.company.GetCompaniesRequest\x1a\x1d.company.GetCompaniesResponse\x12P\n" +
	"\x12UpdateCompanyTitle\x12\".company.UpdateCompanyTitleRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\x13UpdateCompanyStatus\x12#.company.UpdateCompanyStatusRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\rDeleteCompany\x12\x1d.company.DeleteCompanyRequest\x1a\x16.google.protobuf.Empty\x12l\n" +
	"\x17GenerateJoinCompanyCode\x12'.company.GenerateJoinCompanyCodeRequest\x1a(.company.GenerateJoinCompanyCodeResponse\x12H\n" +
	"\vJoinCompany\x12\x1b.company.JoinCompanyRequest\x1a\x1c.company.JoinCompanyResponse\x12`\n" +
	"\x13GetCompanyEmployees\x12#.company.GetCompanyEmployeesRequest\x1a$.company.GetCompanyEmployeesResponse\x12V\n" +
	"\x15RemoveCompanyEmployee\x12%.company.RemoveCompanyEmployeeRequest\x1a\x16.google.protobuf.EmptyB\x15Z\x13proto/company_protob\x06proto3"

var (
	file_company_proto_rawDescOnce sync.Once
	file_company_proto_rawDescData []byte
)

func file_company_proto_rawDescGZIP() []byte {
	file_company_proto_rawDescOnce.Do(func() {
		file_company_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_company_proto_rawDesc), len(file_company_proto_rawDesc)))
	})
	return file_company_proto_rawDescData
}

var file_company_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_company_proto_goTypes = []any{
	(*HealthRequest)(nil),                   // 0: company.HealthRequest
	(*HealthResponse)(nil),                  // 1: company.HealthResponse
	(*CreateCompanyRequest)(nil),            // 2: company.CreateCompanyRequest
	(*CreateCompanyResponse)(nil),           // 3: company.CreateCompanyResponse
	(*GetCompanyRequest)(nil),               // 4: company.GetCompanyRequest
	(*GetCompanyResponse)(nil),              // 5: company.GetCompanyResponse
	(*GetCompaniesRequest)(nil),             // 6: company.GetCompaniesRequest
	(*GetCompaniesResponse)(nil),            // 7: company.GetCompaniesResponse
	(*Company)(nil),                         // 8: company.Company
	(*UpdateCompanyTitleRequest)(nil),       // 9: company.UpdateCompanyTitleRequest
	(*UpdateCompanyStatusRequest)(nil),      // 10: company.UpdateCompanyStatusRequest
	(*DeleteCompanyRequest)(nil),            // 11: company.DeleteCompanyRequest
	(*GenerateJoinCompanyCodeRequest)(nil),  // 12: company.GenerateJoinCompanyCodeRequest
	(*GenerateJoinCompanyCodeResponse)(nil), // 13: company.GenerateJoinCompanyCodeResponse
	(*JoinCompanyRequest)(nil),              // 14: company.JoinCompanyRequest
	(*JoinCompanyResponse)(nil),             // 15: company.JoinCompanyResponse
	(*GetCompanyEmployeesRequest)(nil),      // 16: company.GetCompanyEmployeesRequest
	(*GetCompanyEmployeesResponse)(nil),     // 17: company.GetCompanyEmployeesResponse
	(*RemoveCompanyEmployeeRequest)(nil),    // 18: company.RemoveCompanyEmployeeRequest
	(*emptypb.Empty)(nil),                   // 19: google.protobuf.Empty
}
var file_company_proto_depIdxs = []int32{
	8,  // 0: company.GetCompaniesResponse.companies:type_name -> company.Company
	0,  // 1: company.CompanyService.Health:input_type -> company.HealthRequest
	2,  // 2: company.CompanyService.CreateCompany:input_type -> company.CreateCompanyRequest
	4,  // 3: company.CompanyService.GetCompany:input_type -> company.GetCompanyRequest
	6,  // 4: company.CompanyService.GetCompanies:input_type -> company.GetCompaniesRequest
	9,  // 5: company.CompanyService.UpdateCompanyTitle:input_type -> company.UpdateCompanyTitleRequest
	10, // 6: company.CompanyService.UpdateCompanyStatus:input_type -> company.UpdateCompanyStatusRequest
	11, // 7: company.CompanyService.DeleteCompany:input_type -> company.DeleteCompanyRequest
	12, // 8: company.CompanyService.GenerateJoinCompanyCode:input_type -> company.GenerateJoinCompanyCodeRequest
	14, // 9: company.CompanyService.JoinCompany:input_type -> company.JoinCompanyRequest
	16, // 10: company.CompanyService.GetCompanyEmployees:input_type -> company.GetCompanyEmployeesRequest
	18, // 11: company.CompanyService.RemoveCompanyEmployee:input_type -> company.RemoveCompanyEmployeeRequest
	1,  // 12: company.CompanyService.Health:output_type -> company.HealthResponse
	3,  // 13: company.CompanyService.CreateCompany:output_type -> company.CreateCompanyResponse
	5,  // 14: company.CompanyService.GetCompany:output_type -> company.GetCompanyResponse
	7,  // 15: company.CompanyService.GetCompanies:output_type -> company.GetCompaniesResponse
	19, // 16: company.CompanyService.UpdateCompanyTitle:output_type -> google.protobuf.Empty
	19, // 17: company.CompanyService.UpdateCompanyStatus:output_type -> google.protobuf.Empty
	19, // 18: company.CompanyService.DeleteCompany:output_type -> google.protobuf.Empty
	13, // 19: company.CompanyService.GenerateJoinCompanyCode:output_type -> company.GenerateJoinCompanyCodeResponse
	15, // 20: company.CompanyService.JoinCompany:output_type -> company.JoinCompanyResponse
	17, // 21: company.CompanyService.GetCompanyEmployees:output_type -> company.GetCompanyEmployeesResponse
	19, // 22: company.CompanyService.RemoveCompanyEmployee:output_type -> google.protobuf.Empty
	12, // [12:23] is the sub-list for method output_type
	1,  // [1:12] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_company_proto_init() }
func file_company_proto_init() {
	if File_company_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_company_proto_rawDesc), len(file_company_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_company_proto_goTypes,
		DependencyIndexes: file_company_proto_depIdxs,
		MessageInfos:      file_company_proto_msgTypes,
	}.Build()
	File_company_proto = out.File
	file_company_proto_goTypes = nil
	file_company_proto_depIdxs = nil
}
